// Code generated by go-swagger; DO NOT EDIT.

package identity_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/apiserver/models"
)

// IdentityOpsReGeneratePrivateTokenOKCode is the HTTP code returned for type IdentityOpsReGeneratePrivateTokenOK
const IdentityOpsReGeneratePrivateTokenOKCode int = 200

/*IdentityOpsReGeneratePrivateTokenOK A successful response.

swagger:response identityOpsReGeneratePrivateTokenOK
*/
type IdentityOpsReGeneratePrivateTokenOK struct {

	/*
	  In: Body
	*/
	Payload *models.ModelCommonResp `json:"body,omitempty"`
}

// NewIdentityOpsReGeneratePrivateTokenOK creates IdentityOpsReGeneratePrivateTokenOK with default headers values
func NewIdentityOpsReGeneratePrivateTokenOK() *IdentityOpsReGeneratePrivateTokenOK {

	return &IdentityOpsReGeneratePrivateTokenOK{}
}

// WithPayload adds the payload to the identity ops re generate private token o k response
func (o *IdentityOpsReGeneratePrivateTokenOK) WithPayload(payload *models.ModelCommonResp) *IdentityOpsReGeneratePrivateTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the identity ops re generate private token o k response
func (o *IdentityOpsReGeneratePrivateTokenOK) SetPayload(payload *models.ModelCommonResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IdentityOpsReGeneratePrivateTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*IdentityOpsReGeneratePrivateTokenDefault An unexpected error response.

swagger:response identityOpsReGeneratePrivateTokenDefault
*/
type IdentityOpsReGeneratePrivateTokenDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GatewayruntimeError `json:"body,omitempty"`
}

// NewIdentityOpsReGeneratePrivateTokenDefault creates IdentityOpsReGeneratePrivateTokenDefault with default headers values
func NewIdentityOpsReGeneratePrivateTokenDefault(code int) *IdentityOpsReGeneratePrivateTokenDefault {
	if code <= 0 {
		code = 500
	}

	return &IdentityOpsReGeneratePrivateTokenDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the identity ops re generate private token default response
func (o *IdentityOpsReGeneratePrivateTokenDefault) WithStatusCode(code int) *IdentityOpsReGeneratePrivateTokenDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the identity ops re generate private token default response
func (o *IdentityOpsReGeneratePrivateTokenDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the identity ops re generate private token default response
func (o *IdentityOpsReGeneratePrivateTokenDefault) WithPayload(payload *models.GatewayruntimeError) *IdentityOpsReGeneratePrivateTokenDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the identity ops re generate private token default response
func (o *IdentityOpsReGeneratePrivateTokenDefault) SetPayload(payload *models.GatewayruntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IdentityOpsReGeneratePrivateTokenDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
