// Code generated by go-swagger; DO NOT EDIT.

package identity_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/apiserver/models"
)

// IdentityOpsGeneratePublicTokenOKCode is the HTTP code returned for type IdentityOpsGeneratePublicTokenOK
const IdentityOpsGeneratePublicTokenOKCode int = 200

/*IdentityOpsGeneratePublicTokenOK A successful response.

swagger:response identityOpsGeneratePublicTokenOK
*/
type IdentityOpsGeneratePublicTokenOK struct {

	/*
	  In: Body
	*/
	Payload *models.ModelCommonResp `json:"body,omitempty"`
}

// NewIdentityOpsGeneratePublicTokenOK creates IdentityOpsGeneratePublicTokenOK with default headers values
func NewIdentityOpsGeneratePublicTokenOK() *IdentityOpsGeneratePublicTokenOK {

	return &IdentityOpsGeneratePublicTokenOK{}
}

// WithPayload adds the payload to the identity ops generate public token o k response
func (o *IdentityOpsGeneratePublicTokenOK) WithPayload(payload *models.ModelCommonResp) *IdentityOpsGeneratePublicTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the identity ops generate public token o k response
func (o *IdentityOpsGeneratePublicTokenOK) SetPayload(payload *models.ModelCommonResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IdentityOpsGeneratePublicTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*IdentityOpsGeneratePublicTokenDefault An unexpected error response.

swagger:response identityOpsGeneratePublicTokenDefault
*/
type IdentityOpsGeneratePublicTokenDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GatewayruntimeError `json:"body,omitempty"`
}

// NewIdentityOpsGeneratePublicTokenDefault creates IdentityOpsGeneratePublicTokenDefault with default headers values
func NewIdentityOpsGeneratePublicTokenDefault(code int) *IdentityOpsGeneratePublicTokenDefault {
	if code <= 0 {
		code = 500
	}

	return &IdentityOpsGeneratePublicTokenDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the identity ops generate public token default response
func (o *IdentityOpsGeneratePublicTokenDefault) WithStatusCode(code int) *IdentityOpsGeneratePublicTokenDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the identity ops generate public token default response
func (o *IdentityOpsGeneratePublicTokenDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the identity ops generate public token default response
func (o *IdentityOpsGeneratePublicTokenDefault) WithPayload(payload *models.GatewayruntimeError) *IdentityOpsGeneratePublicTokenDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the identity ops generate public token default response
func (o *IdentityOpsGeneratePublicTokenDefault) SetPayload(payload *models.GatewayruntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IdentityOpsGeneratePublicTokenDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
