// Code generated by go-swagger; DO NOT EDIT.

package identity_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/apiserver/models"
)

// IdentityOpsLoginOKCode is the HTTP code returned for type IdentityOpsLoginOK
const IdentityOpsLoginOKCode int = 200

/*IdentityOpsLoginOK A successful response.

swagger:response identityOpsLoginOK
*/
type IdentityOpsLoginOK struct {

	/*
	  In: Body
	*/
	Payload *models.IdentityLoginResp `json:"body,omitempty"`
}

// NewIdentityOpsLoginOK creates IdentityOpsLoginOK with default headers values
func NewIdentityOpsLoginOK() *IdentityOpsLoginOK {

	return &IdentityOpsLoginOK{}
}

// WithPayload adds the payload to the identity ops login o k response
func (o *IdentityOpsLoginOK) WithPayload(payload *models.IdentityLoginResp) *IdentityOpsLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the identity ops login o k response
func (o *IdentityOpsLoginOK) SetPayload(payload *models.IdentityLoginResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IdentityOpsLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*IdentityOpsLoginDefault An unexpected error response.

swagger:response identityOpsLoginDefault
*/
type IdentityOpsLoginDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GatewayruntimeError `json:"body,omitempty"`
}

// NewIdentityOpsLoginDefault creates IdentityOpsLoginDefault with default headers values
func NewIdentityOpsLoginDefault(code int) *IdentityOpsLoginDefault {
	if code <= 0 {
		code = 500
	}

	return &IdentityOpsLoginDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the identity ops login default response
func (o *IdentityOpsLoginDefault) WithStatusCode(code int) *IdentityOpsLoginDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the identity ops login default response
func (o *IdentityOpsLoginDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the identity ops login default response
func (o *IdentityOpsLoginDefault) WithPayload(payload *models.GatewayruntimeError) *IdentityOpsLoginDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the identity ops login default response
func (o *IdentityOpsLoginDefault) SetPayload(payload *models.GatewayruntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IdentityOpsLoginDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
