// Code generated by go-swagger; DO NOT EDIT.

package identity_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// IdentityOpsListPublicTokenHandlerFunc turns a function with the right signature into a identity ops list public token handler
type IdentityOpsListPublicTokenHandlerFunc func(IdentityOpsListPublicTokenParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn IdentityOpsListPublicTokenHandlerFunc) Handle(params IdentityOpsListPublicTokenParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// IdentityOpsListPublicTokenHandler interface for that can handle valid identity ops list public token params
type IdentityOpsListPublicTokenHandler interface {
	Handle(IdentityOpsListPublicTokenParams, interface{}) middleware.Responder
}

// NewIdentityOpsListPublicToken creates a new http.Handler for the identity ops list public token operation
func NewIdentityOpsListPublicToken(ctx *middleware.Context, handler IdentityOpsListPublicTokenHandler) *IdentityOpsListPublicToken {
	return &IdentityOpsListPublicToken{Context: ctx, Handler: handler}
}

/* IdentityOpsListPublicToken swagger:route GET /user/token/public IdentityOps identityOpsListPublicToken

list user's public_tokens.

*/
type IdentityOpsListPublicToken struct {
	Context *middleware.Context
	Handler IdentityOpsListPublicTokenHandler
}

func (o *IdentityOpsListPublicToken) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewIdentityOpsListPublicTokenParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
