// Code generated by go-swagger; DO NOT EDIT.

package identity_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/apiserver/models"
)

// IdentityOpsDeletePublicTokenOKCode is the HTTP code returned for type IdentityOpsDeletePublicTokenOK
const IdentityOpsDeletePublicTokenOKCode int = 200

/*IdentityOpsDeletePublicTokenOK A successful response.

swagger:response identityOpsDeletePublicTokenOK
*/
type IdentityOpsDeletePublicTokenOK struct {

	/*
	  In: Body
	*/
	Payload *models.ModelCommonResp `json:"body,omitempty"`
}

// NewIdentityOpsDeletePublicTokenOK creates IdentityOpsDeletePublicTokenOK with default headers values
func NewIdentityOpsDeletePublicTokenOK() *IdentityOpsDeletePublicTokenOK {

	return &IdentityOpsDeletePublicTokenOK{}
}

// WithPayload adds the payload to the identity ops delete public token o k response
func (o *IdentityOpsDeletePublicTokenOK) WithPayload(payload *models.ModelCommonResp) *IdentityOpsDeletePublicTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the identity ops delete public token o k response
func (o *IdentityOpsDeletePublicTokenOK) SetPayload(payload *models.ModelCommonResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IdentityOpsDeletePublicTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*IdentityOpsDeletePublicTokenDefault An unexpected error response.

swagger:response identityOpsDeletePublicTokenDefault
*/
type IdentityOpsDeletePublicTokenDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GatewayruntimeError `json:"body,omitempty"`
}

// NewIdentityOpsDeletePublicTokenDefault creates IdentityOpsDeletePublicTokenDefault with default headers values
func NewIdentityOpsDeletePublicTokenDefault(code int) *IdentityOpsDeletePublicTokenDefault {
	if code <= 0 {
		code = 500
	}

	return &IdentityOpsDeletePublicTokenDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the identity ops delete public token default response
func (o *IdentityOpsDeletePublicTokenDefault) WithStatusCode(code int) *IdentityOpsDeletePublicTokenDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the identity ops delete public token default response
func (o *IdentityOpsDeletePublicTokenDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the identity ops delete public token default response
func (o *IdentityOpsDeletePublicTokenDefault) WithPayload(payload *models.GatewayruntimeError) *IdentityOpsDeletePublicTokenDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the identity ops delete public token default response
func (o *IdentityOpsDeletePublicTokenDefault) SetPayload(payload *models.GatewayruntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IdentityOpsDeletePublicTokenDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
