// Code generated by go-swagger; DO NOT EDIT.

package identity_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// IdentityOpsVerifyHandlerFunc turns a function with the right signature into a identity ops verify handler
type IdentityOpsVerifyHandlerFunc func(IdentityOpsVerifyParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn IdentityOpsVerifyHandlerFunc) Handle(params IdentityOpsVerifyParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// IdentityOpsVerifyHandler interface for that can handle valid identity ops verify params
type IdentityOpsVerifyHandler interface {
	Handle(IdentityOpsVerifyParams, interface{}) middleware.Responder
}

// NewIdentityOpsVerify creates a new http.Handler for the identity ops verify operation
func NewIdentityOpsVerify(ctx *middleware.Context, handler IdentityOpsVerifyHandler) *IdentityOpsVerify {
	return &IdentityOpsVerify{Context: ctx, Handler: handler}
}

/* IdentityOpsVerify swagger:route GET /user/verify IdentityOps identityOpsVerify

Verify by session_token.

*/
type IdentityOpsVerify struct {
	Context *middleware.Context
	Handler IdentityOpsVerifyHandler
}

func (o *IdentityOpsVerify) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewIdentityOpsVerifyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
