// Code generated by go-swagger; DO NOT EDIT.

package identity_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/apiserver/models"
)

// IdentityOpsVerifyOKCode is the HTTP code returned for type IdentityOpsVerifyOK
const IdentityOpsVerifyOKCode int = 200

/*IdentityOpsVerifyOK A successful response.

swagger:response identityOpsVerifyOK
*/
type IdentityOpsVerifyOK struct {

	/*
	  In: Body
	*/
	Payload *models.IdentityVerifyResp `json:"body,omitempty"`
}

// NewIdentityOpsVerifyOK creates IdentityOpsVerifyOK with default headers values
func NewIdentityOpsVerifyOK() *IdentityOpsVerifyOK {

	return &IdentityOpsVerifyOK{}
}

// WithPayload adds the payload to the identity ops verify o k response
func (o *IdentityOpsVerifyOK) WithPayload(payload *models.IdentityVerifyResp) *IdentityOpsVerifyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the identity ops verify o k response
func (o *IdentityOpsVerifyOK) SetPayload(payload *models.IdentityVerifyResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IdentityOpsVerifyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*IdentityOpsVerifyDefault An unexpected error response.

swagger:response identityOpsVerifyDefault
*/
type IdentityOpsVerifyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GatewayruntimeError `json:"body,omitempty"`
}

// NewIdentityOpsVerifyDefault creates IdentityOpsVerifyDefault with default headers values
func NewIdentityOpsVerifyDefault(code int) *IdentityOpsVerifyDefault {
	if code <= 0 {
		code = 500
	}

	return &IdentityOpsVerifyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the identity ops verify default response
func (o *IdentityOpsVerifyDefault) WithStatusCode(code int) *IdentityOpsVerifyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the identity ops verify default response
func (o *IdentityOpsVerifyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the identity ops verify default response
func (o *IdentityOpsVerifyDefault) WithPayload(payload *models.GatewayruntimeError) *IdentityOpsVerifyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the identity ops verify default response
func (o *IdentityOpsVerifyDefault) SetPayload(payload *models.GatewayruntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IdentityOpsVerifyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
