// Code generated by go-swagger; DO NOT EDIT.

package identity_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// IdentityOpsReGeneratePrivateTokenHandlerFunc turns a function with the right signature into a identity ops re generate private token handler
type IdentityOpsReGeneratePrivateTokenHandlerFunc func(IdentityOpsReGeneratePrivateTokenParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn IdentityOpsReGeneratePrivateTokenHandlerFunc) Handle(params IdentityOpsReGeneratePrivateTokenParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// IdentityOpsReGeneratePrivateTokenHandler interface for that can handle valid identity ops re generate private token params
type IdentityOpsReGeneratePrivateTokenHandler interface {
	Handle(IdentityOpsReGeneratePrivateTokenParams, interface{}) middleware.Responder
}

// NewIdentityOpsReGeneratePrivateToken creates a new http.Handler for the identity ops re generate private token operation
func NewIdentityOpsReGeneratePrivateToken(ctx *middleware.Context, handler IdentityOpsReGeneratePrivateTokenHandler) *IdentityOpsReGeneratePrivateToken {
	return &IdentityOpsReGeneratePrivateToken{Context: ctx, Handler: handler}
}

/* IdentityOpsReGeneratePrivateToken swagger:route POST /user/token/private IdentityOps identityOpsReGeneratePrivateToken

generate private_token.

*/
type IdentityOpsReGeneratePrivateToken struct {
	Context *middleware.Context
	Handler IdentityOpsReGeneratePrivateTokenHandler
}

func (o *IdentityOpsReGeneratePrivateToken) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewIdentityOpsReGeneratePrivateTokenParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
