// Code generated by go-swagger; DO NOT EDIT.

package identity_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/apiserver/models"
)

// IdentityOpsRegisterOKCode is the HTTP code returned for type IdentityOpsRegisterOK
const IdentityOpsRegisterOKCode int = 200

/*IdentityOpsRegisterOK A successful response.

swagger:response identityOpsRegisterOK
*/
type IdentityOpsRegisterOK struct {

	/*
	  In: Body
	*/
	Payload *models.ModelCommonResp `json:"body,omitempty"`
}

// NewIdentityOpsRegisterOK creates IdentityOpsRegisterOK with default headers values
func NewIdentityOpsRegisterOK() *IdentityOpsRegisterOK {

	return &IdentityOpsRegisterOK{}
}

// WithPayload adds the payload to the identity ops register o k response
func (o *IdentityOpsRegisterOK) WithPayload(payload *models.ModelCommonResp) *IdentityOpsRegisterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the identity ops register o k response
func (o *IdentityOpsRegisterOK) SetPayload(payload *models.ModelCommonResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IdentityOpsRegisterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*IdentityOpsRegisterDefault An unexpected error response.

swagger:response identityOpsRegisterDefault
*/
type IdentityOpsRegisterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GatewayruntimeError `json:"body,omitempty"`
}

// NewIdentityOpsRegisterDefault creates IdentityOpsRegisterDefault with default headers values
func NewIdentityOpsRegisterDefault(code int) *IdentityOpsRegisterDefault {
	if code <= 0 {
		code = 500
	}

	return &IdentityOpsRegisterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the identity ops register default response
func (o *IdentityOpsRegisterDefault) WithStatusCode(code int) *IdentityOpsRegisterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the identity ops register default response
func (o *IdentityOpsRegisterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the identity ops register default response
func (o *IdentityOpsRegisterDefault) WithPayload(payload *models.GatewayruntimeError) *IdentityOpsRegisterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the identity ops register default response
func (o *IdentityOpsRegisterDefault) SetPayload(payload *models.GatewayruntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IdentityOpsRegisterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
