// Code generated by go-swagger; DO NOT EDIT.

package project_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewProjectOpsListParams creates a new ProjectOpsListParams object
//
// There are no default values defined in the spec.
func NewProjectOpsListParams() ProjectOpsListParams {

	return ProjectOpsListParams{}
}

// ProjectOpsListParams contains all the bound params for the project ops list operation
// typically these are obtained from a http.Request
//
// swagger:parameters ProjectOps_List
type ProjectOpsListParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewProjectOpsListParams() beforehand.
func (o *ProjectOpsListParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
