// Code generated by go-swagger; DO NOT EDIT.

package project_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/apiserver/models"
)

// ProjectOpsListServiceOKCode is the HTTP code returned for type ProjectOpsListServiceOK
const ProjectOpsListServiceOKCode int = 200

/*ProjectOpsListServiceOK A successful response.

swagger:response projectOpsListServiceOK
*/
type ProjectOpsListServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.ProjectListServiceResp `json:"body,omitempty"`
}

// NewProjectOpsListServiceOK creates ProjectOpsListServiceOK with default headers values
func NewProjectOpsListServiceOK() *ProjectOpsListServiceOK {

	return &ProjectOpsListServiceOK{}
}

// WithPayload adds the payload to the project ops list service o k response
func (o *ProjectOpsListServiceOK) WithPayload(payload *models.ProjectListServiceResp) *ProjectOpsListServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the project ops list service o k response
func (o *ProjectOpsListServiceOK) SetPayload(payload *models.ProjectListServiceResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProjectOpsListServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ProjectOpsListServiceDefault An unexpected error response.

swagger:response projectOpsListServiceDefault
*/
type ProjectOpsListServiceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GatewayruntimeError `json:"body,omitempty"`
}

// NewProjectOpsListServiceDefault creates ProjectOpsListServiceDefault with default headers values
func NewProjectOpsListServiceDefault(code int) *ProjectOpsListServiceDefault {
	if code <= 0 {
		code = 500
	}

	return &ProjectOpsListServiceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the project ops list service default response
func (o *ProjectOpsListServiceDefault) WithStatusCode(code int) *ProjectOpsListServiceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the project ops list service default response
func (o *ProjectOpsListServiceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the project ops list service default response
func (o *ProjectOpsListServiceDefault) WithPayload(payload *models.GatewayruntimeError) *ProjectOpsListServiceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the project ops list service default response
func (o *ProjectOpsListServiceDefault) SetPayload(payload *models.GatewayruntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProjectOpsListServiceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
