// Code generated by go-swagger; DO NOT EDIT.

package project_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ProjectOpsDeleteProjectHandlerFunc turns a function with the right signature into a project ops delete project handler
type ProjectOpsDeleteProjectHandlerFunc func(ProjectOpsDeleteProjectParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ProjectOpsDeleteProjectHandlerFunc) Handle(params ProjectOpsDeleteProjectParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ProjectOpsDeleteProjectHandler interface for that can handle valid project ops delete project params
type ProjectOpsDeleteProjectHandler interface {
	Handle(ProjectOpsDeleteProjectParams, interface{}) middleware.Responder
}

// NewProjectOpsDeleteProject creates a new http.Handler for the project ops delete project operation
func NewProjectOpsDeleteProject(ctx *middleware.Context, handler ProjectOpsDeleteProjectHandler) *ProjectOpsDeleteProject {
	return &ProjectOpsDeleteProject{Context: ctx, Handler: handler}
}

/* ProjectOpsDeleteProject swagger:route DELETE /project ProjectOps projectOpsDeleteProject

ProjectOpsDeleteProject project ops delete project API

*/
type ProjectOpsDeleteProject struct {
	Context *middleware.Context
	Handler ProjectOpsDeleteProjectHandler
}

func (o *ProjectOpsDeleteProject) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewProjectOpsDeleteProjectParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
