// Code generated by go-swagger; DO NOT EDIT.

package project_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// ProjectOpsListPodsURL generates an URL for the project ops list pods operation
type ProjectOpsListPodsURL struct {
	ProjectName *string
	ServiceName *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ProjectOpsListPodsURL) WithBasePath(bp string) *ProjectOpsListPodsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ProjectOpsListPodsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *ProjectOpsListPodsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/project/service/pod"

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var projectNameQ string
	if o.ProjectName != nil {
		projectNameQ = *o.ProjectName
	}
	if projectNameQ != "" {
		qs.Set("project_name", projectNameQ)
	}

	var serviceNameQ string
	if o.ServiceName != nil {
		serviceNameQ = *o.ServiceName
	}
	if serviceNameQ != "" {
		qs.Set("service_name", serviceNameQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *ProjectOpsListPodsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *ProjectOpsListPodsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *ProjectOpsListPodsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on ProjectOpsListPodsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on ProjectOpsListPodsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *ProjectOpsListPodsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
