// Code generated by go-swagger; DO NOT EDIT.

package project_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ProjectOpsDeleteServiceHandlerFunc turns a function with the right signature into a project ops delete service handler
type ProjectOpsDeleteServiceHandlerFunc func(ProjectOpsDeleteServiceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ProjectOpsDeleteServiceHandlerFunc) Handle(params ProjectOpsDeleteServiceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ProjectOpsDeleteServiceHandler interface for that can handle valid project ops delete service params
type ProjectOpsDeleteServiceHandler interface {
	Handle(ProjectOpsDeleteServiceParams, interface{}) middleware.Responder
}

// NewProjectOpsDeleteService creates a new http.Handler for the project ops delete service operation
func NewProjectOpsDeleteService(ctx *middleware.Context, handler ProjectOpsDeleteServiceHandler) *ProjectOpsDeleteService {
	return &ProjectOpsDeleteService{Context: ctx, Handler: handler}
}

/* ProjectOpsDeleteService swagger:route DELETE /project/service ProjectOps projectOpsDeleteService

ProjectOpsDeleteService project ops delete service API

*/
type ProjectOpsDeleteService struct {
	Context *middleware.Context
	Handler ProjectOpsDeleteServiceHandler
}

func (o *ProjectOpsDeleteService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewProjectOpsDeleteServiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
