// Code generated by go-swagger; DO NOT EDIT.

package project_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/apiserver/models"
)

// ProjectOpsGetServiceOKCode is the HTTP code returned for type ProjectOpsGetServiceOK
const ProjectOpsGetServiceOKCode int = 200

/*ProjectOpsGetServiceOK A successful response.

swagger:response projectOpsGetServiceOK
*/
type ProjectOpsGetServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.ProjectGetServiceResp `json:"body,omitempty"`
}

// NewProjectOpsGetServiceOK creates ProjectOpsGetServiceOK with default headers values
func NewProjectOpsGetServiceOK() *ProjectOpsGetServiceOK {

	return &ProjectOpsGetServiceOK{}
}

// WithPayload adds the payload to the project ops get service o k response
func (o *ProjectOpsGetServiceOK) WithPayload(payload *models.ProjectGetServiceResp) *ProjectOpsGetServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the project ops get service o k response
func (o *ProjectOpsGetServiceOK) SetPayload(payload *models.ProjectGetServiceResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProjectOpsGetServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ProjectOpsGetServiceDefault An unexpected error response.

swagger:response projectOpsGetServiceDefault
*/
type ProjectOpsGetServiceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GatewayruntimeError `json:"body,omitempty"`
}

// NewProjectOpsGetServiceDefault creates ProjectOpsGetServiceDefault with default headers values
func NewProjectOpsGetServiceDefault(code int) *ProjectOpsGetServiceDefault {
	if code <= 0 {
		code = 500
	}

	return &ProjectOpsGetServiceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the project ops get service default response
func (o *ProjectOpsGetServiceDefault) WithStatusCode(code int) *ProjectOpsGetServiceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the project ops get service default response
func (o *ProjectOpsGetServiceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the project ops get service default response
func (o *ProjectOpsGetServiceDefault) WithPayload(payload *models.GatewayruntimeError) *ProjectOpsGetServiceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the project ops get service default response
func (o *ProjectOpsGetServiceDefault) SetPayload(payload *models.GatewayruntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProjectOpsGetServiceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
