// Code generated by go-swagger; DO NOT EDIT.

package authority_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ez-deploy/apiserver/models"
)

// AuthorityOpsListAuthoritiesByResourceHandlerFunc turns a function with the right signature into a authority ops list authorities by resource handler
type AuthorityOpsListAuthoritiesByResourceHandlerFunc func(AuthorityOpsListAuthoritiesByResourceParams, *models.IdentityVerifyResp) middleware.Responder

// Handle executing the request and returning a response
func (fn AuthorityOpsListAuthoritiesByResourceHandlerFunc) Handle(params AuthorityOpsListAuthoritiesByResourceParams, principal *models.IdentityVerifyResp) middleware.Responder {
	return fn(params, principal)
}

// AuthorityOpsListAuthoritiesByResourceHandler interface for that can handle valid authority ops list authorities by resource params
type AuthorityOpsListAuthoritiesByResourceHandler interface {
	Handle(AuthorityOpsListAuthoritiesByResourceParams, *models.IdentityVerifyResp) middleware.Responder
}

// NewAuthorityOpsListAuthoritiesByResource creates a new http.Handler for the authority ops list authorities by resource operation
func NewAuthorityOpsListAuthoritiesByResource(ctx *middleware.Context, handler AuthorityOpsListAuthoritiesByResourceHandler) *AuthorityOpsListAuthoritiesByResource {
	return &AuthorityOpsListAuthoritiesByResource{Context: ctx, Handler: handler}
}

/* AuthorityOpsListAuthoritiesByResource swagger:route GET /authority/resource AuthorityOps authorityOpsListAuthoritiesByResource

AuthorityOpsListAuthoritiesByResource authority ops list authorities by resource API

*/
type AuthorityOpsListAuthoritiesByResource struct {
	Context *middleware.Context
	Handler AuthorityOpsListAuthoritiesByResourceHandler
}

func (o *AuthorityOpsListAuthoritiesByResource) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAuthorityOpsListAuthoritiesByResourceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.IdentityVerifyResp
	if uprinc != nil {
		principal = uprinc.(*models.IdentityVerifyResp) // this is really a models.IdentityVerifyResp, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
