// Code generated by go-swagger; DO NOT EDIT.

package authority_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// AuthorityOpsListAuthoritiesByIdentityURL generates an URL for the authority ops list authorities by identity operation
type AuthorityOpsListAuthoritiesByIdentityURL struct {
	Email *string
	Name  *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *AuthorityOpsListAuthoritiesByIdentityURL) WithBasePath(bp string) *AuthorityOpsListAuthoritiesByIdentityURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *AuthorityOpsListAuthoritiesByIdentityURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *AuthorityOpsListAuthoritiesByIdentityURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/authority/identity"

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var emailQ string
	if o.Email != nil {
		emailQ = *o.Email
	}
	if emailQ != "" {
		qs.Set("email", emailQ)
	}

	var nameQ string
	if o.Name != nil {
		nameQ = *o.Name
	}
	if nameQ != "" {
		qs.Set("name", nameQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *AuthorityOpsListAuthoritiesByIdentityURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *AuthorityOpsListAuthoritiesByIdentityURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *AuthorityOpsListAuthoritiesByIdentityURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on AuthorityOpsListAuthoritiesByIdentityURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on AuthorityOpsListAuthoritiesByIdentityURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *AuthorityOpsListAuthoritiesByIdentityURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
