// Code generated by go-swagger; DO NOT EDIT.

package authority_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/apiserver/models"
)

// AuthorityOpsSetAuthoritiesOKCode is the HTTP code returned for type AuthorityOpsSetAuthoritiesOK
const AuthorityOpsSetAuthoritiesOKCode int = 200

/*AuthorityOpsSetAuthoritiesOK A successful response.

swagger:response authorityOpsSetAuthoritiesOK
*/
type AuthorityOpsSetAuthoritiesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ModelCommonResp `json:"body,omitempty"`
}

// NewAuthorityOpsSetAuthoritiesOK creates AuthorityOpsSetAuthoritiesOK with default headers values
func NewAuthorityOpsSetAuthoritiesOK() *AuthorityOpsSetAuthoritiesOK {

	return &AuthorityOpsSetAuthoritiesOK{}
}

// WithPayload adds the payload to the authority ops set authorities o k response
func (o *AuthorityOpsSetAuthoritiesOK) WithPayload(payload *models.ModelCommonResp) *AuthorityOpsSetAuthoritiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the authority ops set authorities o k response
func (o *AuthorityOpsSetAuthoritiesOK) SetPayload(payload *models.ModelCommonResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthorityOpsSetAuthoritiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AuthorityOpsSetAuthoritiesDefault An unexpected error response.

swagger:response authorityOpsSetAuthoritiesDefault
*/
type AuthorityOpsSetAuthoritiesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GatewayruntimeError `json:"body,omitempty"`
}

// NewAuthorityOpsSetAuthoritiesDefault creates AuthorityOpsSetAuthoritiesDefault with default headers values
func NewAuthorityOpsSetAuthoritiesDefault(code int) *AuthorityOpsSetAuthoritiesDefault {
	if code <= 0 {
		code = 500
	}

	return &AuthorityOpsSetAuthoritiesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the authority ops set authorities default response
func (o *AuthorityOpsSetAuthoritiesDefault) WithStatusCode(code int) *AuthorityOpsSetAuthoritiesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the authority ops set authorities default response
func (o *AuthorityOpsSetAuthoritiesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the authority ops set authorities default response
func (o *AuthorityOpsSetAuthoritiesDefault) WithPayload(payload *models.GatewayruntimeError) *AuthorityOpsSetAuthoritiesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the authority ops set authorities default response
func (o *AuthorityOpsSetAuthoritiesDefault) SetPayload(payload *models.GatewayruntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthorityOpsSetAuthoritiesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
