// Code generated by go-swagger; DO NOT EDIT.

package authority_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AuthorityOpsSetAuthoritiesHandlerFunc turns a function with the right signature into a authority ops set authorities handler
type AuthorityOpsSetAuthoritiesHandlerFunc func(AuthorityOpsSetAuthoritiesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AuthorityOpsSetAuthoritiesHandlerFunc) Handle(params AuthorityOpsSetAuthoritiesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AuthorityOpsSetAuthoritiesHandler interface for that can handle valid authority ops set authorities params
type AuthorityOpsSetAuthoritiesHandler interface {
	Handle(AuthorityOpsSetAuthoritiesParams, interface{}) middleware.Responder
}

// NewAuthorityOpsSetAuthorities creates a new http.Handler for the authority ops set authorities operation
func NewAuthorityOpsSetAuthorities(ctx *middleware.Context, handler AuthorityOpsSetAuthoritiesHandler) *AuthorityOpsSetAuthorities {
	return &AuthorityOpsSetAuthorities{Context: ctx, Handler: handler}
}

/* AuthorityOpsSetAuthorities swagger:route POST /authority AuthorityOps authorityOpsSetAuthorities

AuthorityOpsSetAuthorities authority ops set authorities API

*/
type AuthorityOpsSetAuthorities struct {
	Context *middleware.Context
	Handler AuthorityOpsSetAuthoritiesHandler
}

func (o *AuthorityOpsSetAuthorities) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAuthorityOpsSetAuthoritiesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
