// Code generated by go-swagger; DO NOT EDIT.

package authority_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/apiserver/models"
)

// AuthorityOpsListAuthoritiesByIdentityOKCode is the HTTP code returned for type AuthorityOpsListAuthoritiesByIdentityOK
const AuthorityOpsListAuthoritiesByIdentityOKCode int = 200

/*AuthorityOpsListAuthoritiesByIdentityOK A successful response.

swagger:response authorityOpsListAuthoritiesByIdentityOK
*/
type AuthorityOpsListAuthoritiesByIdentityOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuthorityListAuthoritiesResp `json:"body,omitempty"`
}

// NewAuthorityOpsListAuthoritiesByIdentityOK creates AuthorityOpsListAuthoritiesByIdentityOK with default headers values
func NewAuthorityOpsListAuthoritiesByIdentityOK() *AuthorityOpsListAuthoritiesByIdentityOK {

	return &AuthorityOpsListAuthoritiesByIdentityOK{}
}

// WithPayload adds the payload to the authority ops list authorities by identity o k response
func (o *AuthorityOpsListAuthoritiesByIdentityOK) WithPayload(payload *models.AuthorityListAuthoritiesResp) *AuthorityOpsListAuthoritiesByIdentityOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the authority ops list authorities by identity o k response
func (o *AuthorityOpsListAuthoritiesByIdentityOK) SetPayload(payload *models.AuthorityListAuthoritiesResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthorityOpsListAuthoritiesByIdentityOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AuthorityOpsListAuthoritiesByIdentityDefault An unexpected error response.

swagger:response authorityOpsListAuthoritiesByIdentityDefault
*/
type AuthorityOpsListAuthoritiesByIdentityDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GatewayruntimeError `json:"body,omitempty"`
}

// NewAuthorityOpsListAuthoritiesByIdentityDefault creates AuthorityOpsListAuthoritiesByIdentityDefault with default headers values
func NewAuthorityOpsListAuthoritiesByIdentityDefault(code int) *AuthorityOpsListAuthoritiesByIdentityDefault {
	if code <= 0 {
		code = 500
	}

	return &AuthorityOpsListAuthoritiesByIdentityDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the authority ops list authorities by identity default response
func (o *AuthorityOpsListAuthoritiesByIdentityDefault) WithStatusCode(code int) *AuthorityOpsListAuthoritiesByIdentityDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the authority ops list authorities by identity default response
func (o *AuthorityOpsListAuthoritiesByIdentityDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the authority ops list authorities by identity default response
func (o *AuthorityOpsListAuthoritiesByIdentityDefault) WithPayload(payload *models.GatewayruntimeError) *AuthorityOpsListAuthoritiesByIdentityDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the authority ops list authorities by identity default response
func (o *AuthorityOpsListAuthoritiesByIdentityDefault) SetPayload(payload *models.GatewayruntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthorityOpsListAuthoritiesByIdentityDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
