// Code generated by go-swagger; DO NOT EDIT.

package authority_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/apiserver/models"
)

// AuthorityOpsDeleteAuthoritiesOKCode is the HTTP code returned for type AuthorityOpsDeleteAuthoritiesOK
const AuthorityOpsDeleteAuthoritiesOKCode int = 200

/*AuthorityOpsDeleteAuthoritiesOK A successful response.

swagger:response authorityOpsDeleteAuthoritiesOK
*/
type AuthorityOpsDeleteAuthoritiesOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuthorityDeleteAuthoritiesResp `json:"body,omitempty"`
}

// NewAuthorityOpsDeleteAuthoritiesOK creates AuthorityOpsDeleteAuthoritiesOK with default headers values
func NewAuthorityOpsDeleteAuthoritiesOK() *AuthorityOpsDeleteAuthoritiesOK {

	return &AuthorityOpsDeleteAuthoritiesOK{}
}

// WithPayload adds the payload to the authority ops delete authorities o k response
func (o *AuthorityOpsDeleteAuthoritiesOK) WithPayload(payload *models.AuthorityDeleteAuthoritiesResp) *AuthorityOpsDeleteAuthoritiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the authority ops delete authorities o k response
func (o *AuthorityOpsDeleteAuthoritiesOK) SetPayload(payload *models.AuthorityDeleteAuthoritiesResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthorityOpsDeleteAuthoritiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AuthorityOpsDeleteAuthoritiesDefault An unexpected error response.

swagger:response authorityOpsDeleteAuthoritiesDefault
*/
type AuthorityOpsDeleteAuthoritiesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GatewayruntimeError `json:"body,omitempty"`
}

// NewAuthorityOpsDeleteAuthoritiesDefault creates AuthorityOpsDeleteAuthoritiesDefault with default headers values
func NewAuthorityOpsDeleteAuthoritiesDefault(code int) *AuthorityOpsDeleteAuthoritiesDefault {
	if code <= 0 {
		code = 500
	}

	return &AuthorityOpsDeleteAuthoritiesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the authority ops delete authorities default response
func (o *AuthorityOpsDeleteAuthoritiesDefault) WithStatusCode(code int) *AuthorityOpsDeleteAuthoritiesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the authority ops delete authorities default response
func (o *AuthorityOpsDeleteAuthoritiesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the authority ops delete authorities default response
func (o *AuthorityOpsDeleteAuthoritiesDefault) WithPayload(payload *models.GatewayruntimeError) *AuthorityOpsDeleteAuthoritiesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the authority ops delete authorities default response
func (o *AuthorityOpsDeleteAuthoritiesDefault) SetPayload(payload *models.GatewayruntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthorityOpsDeleteAuthoritiesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
