// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthorityListAuthoritiesResp authority list authorities resp
//
// swagger:model authorityListAuthoritiesResp
type AuthorityListAuthoritiesResp struct {

	// authorities
	Authorities *AuthorityAuthorities `json:"authorities,omitempty"`

	// error
	Error *ModelError `json:"error,omitempty"`
}

// Validate validates this authority list authorities resp
func (m *AuthorityListAuthoritiesResp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthorities(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthorityListAuthoritiesResp) validateAuthorities(formats strfmt.Registry) error {
	if swag.IsZero(m.Authorities) { // not required
		return nil
	}

	if m.Authorities != nil {
		if err := m.Authorities.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("authorities")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("authorities")
			}
			return err
		}
	}

	return nil
}

func (m *AuthorityListAuthoritiesResp) validateError(formats strfmt.Registry) error {
	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if m.Error != nil {
		if err := m.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this authority list authorities resp based on the context it is used
func (m *AuthorityListAuthoritiesResp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAuthorities(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthorityListAuthoritiesResp) contextValidateAuthorities(ctx context.Context, formats strfmt.Registry) error {

	if m.Authorities != nil {
		if err := m.Authorities.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("authorities")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("authorities")
			}
			return err
		}
	}

	return nil
}

func (m *AuthorityListAuthoritiesResp) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if m.Error != nil {
		if err := m.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuthorityListAuthoritiesResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthorityListAuthoritiesResp) UnmarshalBinary(b []byte) error {
	var res AuthorityListAuthoritiesResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
