// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthorityAuthorities authority authorities
//
// swagger:model authorityAuthorities
type AuthorityAuthorities struct {

	// authorities
	Authorities []*ModelAuthority `json:"authorities"`
}

// Validate validates this authority authorities
func (m *AuthorityAuthorities) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthorities(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthorityAuthorities) validateAuthorities(formats strfmt.Registry) error {
	if swag.IsZero(m.Authorities) { // not required
		return nil
	}

	for i := 0; i < len(m.Authorities); i++ {
		if swag.IsZero(m.Authorities[i]) { // not required
			continue
		}

		if m.Authorities[i] != nil {
			if err := m.Authorities[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("authorities" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("authorities" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this authority authorities based on the context it is used
func (m *AuthorityAuthorities) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAuthorities(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthorityAuthorities) contextValidateAuthorities(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Authorities); i++ {

		if m.Authorities[i] != nil {
			if err := m.Authorities[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("authorities" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("authorities" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuthorityAuthorities) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthorityAuthorities) UnmarshalBinary(b []byte) error {
	var res AuthorityAuthorities
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
