// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteAuthoritiesRespFailMessages delete authorities resp fail messages
//
// swagger:model DeleteAuthoritiesRespFailMessages
type DeleteAuthoritiesRespFailMessages struct {

	// authority
	Authority *ModelAuthority `json:"authority,omitempty"`

	// error
	Error *ModelError `json:"error,omitempty"`
}

// Validate validates this delete authorities resp fail messages
func (m *DeleteAuthoritiesRespFailMessages) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthority(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeleteAuthoritiesRespFailMessages) validateAuthority(formats strfmt.Registry) error {
	if swag.IsZero(m.Authority) { // not required
		return nil
	}

	if m.Authority != nil {
		if err := m.Authority.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("authority")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("authority")
			}
			return err
		}
	}

	return nil
}

func (m *DeleteAuthoritiesRespFailMessages) validateError(formats strfmt.Registry) error {
	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if m.Error != nil {
		if err := m.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete authorities resp fail messages based on the context it is used
func (m *DeleteAuthoritiesRespFailMessages) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAuthority(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeleteAuthoritiesRespFailMessages) contextValidateAuthority(ctx context.Context, formats strfmt.Registry) error {

	if m.Authority != nil {
		if err := m.Authority.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("authority")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("authority")
			}
			return err
		}
	}

	return nil
}

func (m *DeleteAuthoritiesRespFailMessages) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if m.Error != nil {
		if err := m.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeleteAuthoritiesRespFailMessages) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteAuthoritiesRespFailMessages) UnmarshalBinary(b []byte) error {
	var res DeleteAuthoritiesRespFailMessages
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
