// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IdentityGeneratePublicTokenReq identity generate public token req
//
// swagger:model identityGeneratePublicTokenReq
type IdentityGeneratePublicTokenReq struct {

	// api token
	APIToken *ModelAPIToken `json:"api_token,omitempty"`

	// identity
	Identity *ModelIdentity `json:"identity,omitempty"`
}

// Validate validates this identity generate public token req
func (m *IdentityGeneratePublicTokenReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPIToken(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIdentity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IdentityGeneratePublicTokenReq) validateAPIToken(formats strfmt.Registry) error {
	if swag.IsZero(m.APIToken) { // not required
		return nil
	}

	if m.APIToken != nil {
		if err := m.APIToken.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("api_token")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("api_token")
			}
			return err
		}
	}

	return nil
}

func (m *IdentityGeneratePublicTokenReq) validateIdentity(formats strfmt.Registry) error {
	if swag.IsZero(m.Identity) { // not required
		return nil
	}

	if m.Identity != nil {
		if err := m.Identity.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("identity")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("identity")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this identity generate public token req based on the context it is used
func (m *IdentityGeneratePublicTokenReq) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAPIToken(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIdentity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IdentityGeneratePublicTokenReq) contextValidateAPIToken(ctx context.Context, formats strfmt.Registry) error {

	if m.APIToken != nil {
		if err := m.APIToken.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("api_token")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("api_token")
			}
			return err
		}
	}

	return nil
}

func (m *IdentityGeneratePublicTokenReq) contextValidateIdentity(ctx context.Context, formats strfmt.Registry) error {

	if m.Identity != nil {
		if err := m.Identity.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("identity")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("identity")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IdentityGeneratePublicTokenReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IdentityGeneratePublicTokenReq) UnmarshalBinary(b []byte) error {
	var res IdentityGeneratePublicTokenReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
