// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelPod model pod
//
// swagger:model modelPod
type ModelPod struct {

	// age
	Age string `json:"age,omitempty"`

	// machine name
	MachineName string `json:"machine_name,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this model pod
func (m *ModelPod) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model pod based on context it is used
func (m *ModelPod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelPod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelPod) UnmarshalBinary(b []byte) error {
	var res ModelPod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
