// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelProject model project
//
// swagger:model modelProject
type ModelProject struct {

	// describe
	Describe string `json:"describe,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this model project
func (m *ModelProject) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model project based on context it is used
func (m *ModelProject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelProject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelProject) UnmarshalBinary(b []byte) error {
	var res ModelProject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
